# Data Incompleta

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
#Cómo detectar la data que falta

#Revisemos la data
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/Lab 2 - Data Preparation/credito.csv")

In [ ]:
data.sample(10)

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV,perfil
84,1.51409,14.25,3.09,2.08,72.28,1.10,7.08,0.00,0.00,2
10,1.51571,12.72,3.46,1.56,73.20,0.67,8.09,0.00,0.24,1
58,1.51754,13.48,3.74,1.17,72.99,0.59,8.03,0.00,0.00,1
111,1.52739,11.02,0.00,0.75,73.08,0.00,14.96,0.00,0.00,2
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.00,1
43,1.52210,13.73,3.84,0.72,71.76,0.17,9.74,0.00,0.00,1
202,1.51514,14.85,0.00,2.42,73.72,0.00,8.39,0.56,0.00,7
12,1.51589,12.88,3.43,1.40,73.28,0.69,8.05,0.00,0.24,1
66,1.52152,13.05,3.65,0.87,72.22,0.19,9.85,0.00,0.17,1
113,1.51892,13.46,3.83,1.26,72.55,0.57,8.21,0.00,0.14,2

In [ ]:
print(data.shape)

(214, 10)

In [ ]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
data.columns

Index(['ID', 'oferta', 'cuota', 'deuda', 'p_default', 'PDI', 'ingreso',
       'deuda_mora', 'LTV', 'perfil'],
      dtype='object')

In [ ]:
data.index

RangeIndex(start=0, stop=214, step=1)

##  Duplicate values

In [ ]:
help(pd.DataFrame.duplicated)

Help on function duplicated in module pandas.core.frame:

duplicated(self, subset: 'Hashable | Sequence[Hashable] | None' = None, keep: "Literal['first'] | Literal['last'] | Literal[False]" = 'first') -> 'Series'
    Return boolean Series denoting duplicate rows.

    Considering certain columns is optional.

    Parameters
    ----------
    subset : column label or sequence of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns.
    keep : {'first', 'last', False}, default 'first'
        Determines which duplicates (if any) to mark.

        - ``first`` : Mark duplicates as ``True`` except for the first occurrence.
        - ``last`` : Mark duplicates as ``True`` except for the last occurrence.
        - False : Mark all duplicates as ``True``.

    Returns
    -------
    Series
        Boolean series for each duplicated rows.

    See Also
    --------
    Index.duplicated : Equivalent method on index.
    Series.duplicated : Equivalent method on Series.
    Series.drop_duplicates : Remove duplicate values from Series.
    DataFrame.drop_duplicates : Remove duplicate values from DataFrame.

    Examples
    --------
    Consider dataset containing ramen rating.

    >>> df = pd.DataFrame({
    ...     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    ...     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    ...     'rating': [4, 4, 3.5, 15, 5]
    ... })
    >>> df
        brand style  rating
    0  Yum Yum   cup     4.0
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    By default, for each set of duplicated values, the first occurrence
    is set on False and all others on True.

    >>> df.duplicated()
    0    False
    1     True
    2    False
    3    False
    4    False
    dtype: bool

    By using 'last', the last occurrence of each set of duplicated values
    is set on False and all others on True.

    >>> df.duplicated(keep='last')
    0     True
    1    False
    2    False
    3    False
    4    False
    dtype: bool

    By setting ``keep`` on False, all duplicates are True.

    >>> df.duplicated(keep=False)
    0     True
    1     True
    2    False
    3    False
    4    False
    dtype: bool

    To find duplicates on specific column(s), use ``subset``.

    >>> df.duplicated(subset=['brand'])
    0    False
    1     True
    2    False
    3     True
    4     True
    dtype: bool

In [ ]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
209    False
210    False
211    False
212    False
213    False
Length: 214, dtype: bool

In [ ]:
data[data.duplicated()]

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV,perfil
39,1.52213,14.21,3.82,0.47,71.77,0.11,9.57,0.0,0.0,1

In [ ]:
help(pd.DataFrame.drop_duplicates)

Help on function drop_duplicates in module pandas.core.frame:

drop_duplicates(self, subset: 'Hashable | Sequence[Hashable] | None' = None, *, keep: 'DropKeep' = 'first', inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'DataFrame | None'
    Return DataFrame with duplicate rows removed.

    Considering certain columns is optional. Indexes, including time indexes
    are ignored.

    Parameters
    ----------
    subset : column label or sequence of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns.
    keep : {'first', 'last', ``False``}, default 'first'
        Determines which duplicates (if any) to keep.

        - 'first' : Drop duplicates except for the first occurrence.
        - 'last' : Drop duplicates except for the last occurrence.
        - ``False`` : Drop all duplicates.

    inplace : bool, default ``False``
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

    Returns
    -------
    DataFrame or None
        DataFrame with duplicates removed or None if ``inplace=True``.

    See Also
    --------
    DataFrame.value_counts: Count unique combinations of columns.

    Examples
    --------
    Consider dataset containing ramen rating.

    >>> df = pd.DataFrame({
    ...     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    ...     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    ...     'rating': [4, 4, 3.5, 15, 5]
    ... })
    >>> df
        brand style  rating
    0  Yum Yum   cup     4.0
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    By default, it removes duplicate rows based on all columns.

    >>> df.drop_duplicates()
        brand style  rating
    0  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    To remove duplicates on specific column(s), use ``subset``.

    >>> df.drop_duplicates(subset=['brand'])
        brand style  rating
    0  Yum Yum   cup     4.0
    2  Indomie   cup     3.5

    To remove duplicates and keep last occurrences, use ``keep``.

    >>> df.drop_duplicates(subset=['brand', 'style'], keep='last')
        brand style  rating
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    4  Indomie  pack     5.0

In [ ]:
## proceed with caution!

data.drop_duplicates(inplace=True)
print(data.shape)

(213, 10)

## Missing Values

In [ ]:
data.describe()

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV,perfil
count,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000
mean,1.518348,13.404085,2.679202,1.449484,72.655070,0.498873,8.954085,0.175869,0.057277,2.788732
std,0.003033,0.816662,1.443691,0.495925,0.773998,0.653185,1.425882,0.498245,0.097589,2.105130
min,1.511150,10.730000,0.000000,0.290000,69.810000,0.000000,5.430000,0.000000,0.000000,1.000000
25%,1.516520,12.900000,2.090000,1.190000,72.280000,0.130000,8.240000,0.000000,0.000000,1.000000
50%,1.517680,13.300000,3.480000,1.360000,72.790000,0.560000,8.600000,0.000000,0.000000,2.000000
75%,1.519150,13.810000,3.600000,1.630000,73.090000,0.610000,9.150000,0.000000,0.100000,3.000000
max,1.533930,17.380000,4.490000,3.500000,75.410000,6.210000,16.190000,3.150000,0.510000,7.000000

In [ ]:
data.groupby("perfil").mean()

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV
perfil,,,,,,,,,
1,1.518669,13.228261,3.548551,1.173913,72.631449,0.452319,8.786087,0.012899,0.057826
2,1.518619,13.111711,3.002105,1.408158,72.598026,0.521053,9.073684,0.050263,0.079737
3,1.517964,13.437059,3.543529,1.201176,72.404706,0.406471,8.782941,0.008824,0.057059
5,1.518928,12.827692,0.773846,2.033846,72.366154,1.470000,10.123846,0.187692,0.060769
6,1.517456,14.646667,1.305556,1.366667,73.206667,0.000000,9.356667,0.000000,0.000000
7,1.517116,14.442069,0.538276,2.122759,72.965862,0.325172,8.491379,1.040000,0.013448

In [ ]:
#Create some missing values
import numpy as np
data.iloc[::3,-1]=np.nan #not a number (to every third element)
data.iloc[::4,0]=np.nan

In [ ]:
data.head(10)

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV,perfil
0,NaN,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.00,NaN
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.00,1.0
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.00,1.0
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.00,NaN
4,NaN,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.00,1.0
5,1.51596,12.79,3.61,1.62,72.97,0.64,8.07,0.0,0.26,1.0
6,1.51743,13.30,3.60,1.14,73.09,0.58,8.17,0.0,0.00,NaN
7,1.51756,13.15,3.61,1.05,73.24,0.57,8.24,0.0,0.00,1.0
8,NaN,14.04,3.58,1.37,72.08,0.56,8.30,0.0,0.00,1.0
9,1.51755,13.00,3.60,1.36,72.99,0.57,8.40,0.0,0.11,NaN

In [ ]:
#To make detecting missing values easier (and across different array dtypes),
#pandas provides the isna() and notna() functions,
#which are also methods on Series and DataFrame objects

type(data['perfil'])

pandas.core.series.Series

In [ ]:
data.isna().any()

ID             True
oferta        False
cuota         False
deuda         False
p_default     False
PDI           False
ingreso       False
deuda_mora    False
LTV           False
perfil         True
dtype: bool

In [ ]:
#or you can ask for who is notNAN
data['perfil'].notna()

0      False
1       True
2       True
3      False
4       True
       ...
209     True
210     True
211    False
212     True
213     True
Name: perfil, Length: 213, dtype: bool

In [ ]:
data.isna().head() #on the entire dataframe

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV,perfil
0,True,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True
4,True,False,False,False,False,False,False,False,False,False

In [ ]:
#a few comments:
##When summing data, NA (missing) values will be treated as zero.
##NA groups in GroupBy are automatically excluded

data.groupby("perfil").min()

#In other words, there will never be an “NA group”
#This was not the case in older versions of pandas

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV
perfil,,,,,,,,,
1.0,1.51215,12.56,2.81,0.47,71.35,0.00,7.78,0.0,0.0
2.0,1.51409,11.02,0.00,0.75,70.16,0.00,7.08,0.0,0.0
3.0,1.51610,12.16,3.36,0.65,71.36,0.06,8.32,0.0,0.0
5.0,1.51316,11.56,0.00,1.40,70.48,0.32,6.96,0.0,0.0
6.0,1.51299,13.79,0.00,0.56,72.37,0.00,7.59,0.0,0.0
7.0,1.51508,11.95,0.00,1.19,70.26,0.00,5.43,0.0,0.0

In [ ]:
data.groupby("perfil").min()

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV
perfil,,,,,,,,,
1.0,1.51215,12.56,2.81,0.47,71.35,0.00,7.78,0.0,0.0
2.0,1.51409,11.02,0.00,0.75,70.16,0.00,7.08,0.0,0.0
3.0,1.51610,12.16,3.36,0.65,71.36,0.06,8.32,0.0,0.0
5.0,1.51316,11.56,0.00,1.40,70.48,0.32,6.96,0.0,0.0
6.0,1.51299,13.79,0.00,0.56,72.37,0.00,7.59,0.0,0.0
7.0,1.51508,11.95,0.00,1.19,70.26,0.00,5.43,0.0,0.0

In [ ]:
data.describe()

,ID,oferta,cuota,deuda,p_default,PDI,ingreso,deuda_mora,LTV,perfil
count,159.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,142.000000
mean,1.518386,13.404085,2.679202,1.449484,72.655070,0.498873,8.954085,0.175869,0.057277,2.802817
std,0.003270,0.816662,1.443691,0.495925,0.773998,0.653185,1.425882,0.498245,0.097589,2.121285
min,1.511150,10.730000,0.000000,0.290000,69.810000,0.000000,5.430000,0.000000,0.000000,1.000000
25%,1.516460,12.900000,2.090000,1.190000,72.280000,0.130000,8.240000,0.000000,0.000000,1.000000
50%,1.517640,13.300000,3.480000,1.360000,72.790000,0.560000,8.600000,0.000000,0.000000,2.000000
75%,1.519130,13.810000,3.600000,1.630000,73.090000,0.610000,9.150000,0.000000,0.100000,3.000000
max,1.533930,17.380000,4.490000,3.500000,75.410000,6.210000,16.190000,3.150000,0.510000,7.000000

## Some alternatives to deal with missing values

## 1. Drop

In [ ]:
#How to use "dropna" method to Remove missing values from a dataframe.

data = pd.read_csv("glass.csv")
data.iloc[::3,-1]=np.nan #not a number (to every third element)

data
#Drop the rows where at least one element is missing.
data_drop=data.dropna(axis=0) #1/3 has been removed
#data_drop
#print(len(data), len(data_drop))

#Drop the columns where at least one element is missing.
data_drop=data.dropna(axis=1) # or axis=1 #remove the  column
data_drop

#Drop the rows where all elements are missing.
#data_drop=data.dropna(how='all')
#data_drop
#Define in which columns to look for missing values.
#data.dropna(subset=['RI','Type'])

#Keep the DataFrame with valid entries in the same variable
#that means that dropna changed data
#data.dropna(inplace=True)

#print out your data

#print(data.shape)
#print(data.head())

#print(data_drop.shape)
#print(data_drop.head())

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 9 columns]

### 2. SUBSTITUTION:  (Be careful using this approach!)

How to use "fillna" to replace missing values

In [ ]:

data = pd.read_csv("/content/drive/MyDrive/Lab 2 - Data Preparation/glass.csv")
data.iloc[::3,-1]=np.nan

data
data.fillna(999)

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe   Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0  999.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0    1.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0    1.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0  999.0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0    1.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...    ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0    7.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0  999.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0    7.0
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0    7.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0  999.0

[214 rows x 10 columns]

In [ ]:
#if I want to replace with different rules in different columns
data.iloc[::4,0]=np.nan #not a number (to every forth element)
data

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0        NaN  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0   NaN
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0   1.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0   1.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0   NaN
4        NaN  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0   1.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0   7.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0   NaN
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0   7.0
212      NaN  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0   7.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0   NaN

[214 rows x 10 columns]

In [ ]:
values = {'Type': 33} #you can add more rules here for the other columns
data.fillna(value=values).head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0      NaN  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0  33.0
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0   1.0
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0   1.0
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0  33.0
4      NaN  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0   1.0

In [ ]:
values = {'Type':999, "RI": -1} #you can add more rules here for the other columns
data.fillna(value=values)

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe   Type
0   -1.00000  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0  999.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0    1.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0    1.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0  999.0
4   -1.00000  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0    1.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...    ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0    7.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0  999.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0    7.0
212 -1.00000  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0    7.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0  999.0

[214 rows x 10 columns]

In [ ]:
data.fillna(data.mean()[["Type"]])#replace missing value with the column mean

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe     Type
0        NaN  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0  2.78169
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0  1.00000
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0  1.00000
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0  2.78169
4        NaN  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0  1.00000
..       ...    ...   ...   ...    ...   ...   ...   ...  ...      ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0  7.00000
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0  2.78169
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0  7.00000
212      NaN  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0  7.00000
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0  2.78169

[214 rows x 10 columns]

In [ ]:
#data.head()
data.fillna(data.mean()["RI":"Type"])

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe     Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0  2.78169
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0  1.00000
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0  1.00000
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0  2.78169
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0  1.00000
..       ...    ...   ...   ...    ...   ...   ...   ...  ...      ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0  7.00000
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0  2.78169
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0  7.00000
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0  7.00000
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0  2.78169

[214 rows x 10 columns]

In [ ]:
# interpolate()

 <table>
  <tr>
    <td><img src="series_before_interpolate.png"></td>
    <td><img src="series_interpolate.png"> </td>
  </tr>
  <tr>
    <td style="text-align:center">TS with missing values</td>
    <td style="text-align:center">After interpolation</td>
  </tr>
</table>