## Ejercicio 1

In [12]:
import numpy as np

# Ejercicio 1: Función para calcular el GCD
def calcular_gcd(m, n):
    while n:
        m, n = n, m % n
    return m

print(f"El GCD de 48 y 18 es: {calcular_gcd(48, 18)}")

El GCD de 48 y 18 es: 6

In [13]:
# Ejercicio 2: NumPy
# 1. Crear arreglo aleatorio de longitud 100
arreglo = np.random.rand(100)

In [14]:
# 2. Ordenar el arreglo
arreglo_ordenado = np.sort(arreglo)

In [15]:
# 3. Calcular métricas
media = np.mean(arreglo)
mediana = np.median(arreglo)
varianza = np.var(arreglo)
print(f"\nEstadísticas NumPy:\nMedia: {media:.4f}\nMediana: {mediana:.4f}\nVarianza: {varianza:.4f}")

Estadísticas NumPy:
Media: 0.5080
Mediana: 0.5482
Varianza: 0.0812

## Ejercicio 2

In [2]:
import pandas as pd
from sklearn.datasets import load_iris

# Ejercicio 3: Pandas
# 1 e 2. Importar y añadir nombres de columnas
iris_data = load_iris()
df = pd.DataFrame(iris_data.data, columns=['sepal length', 'sepal width', 'petal length', 'petal width'])

# 3. Crear columna de relación (ratio) entre sépalo y pétalo
df['sepal_petal_ratio'] = df['sepal length'] / df['petal length']

# 4. Añadir columna 'target' basada en la especie (Iris-Setosa suele ser el ID 0 en sklearn)
# Nota: asignamos 1 si es setosa, 0 si no.
df['target'] = (iris_data.target == 0).astype(int)

print("Primeras filas del DataFrame Iris:")
print(df.head())

Primeras filas del DataFrame Iris:
   sepal length  sepal width  petal length  petal width  sepal_petal_ratio  \
0           5.1          3.5           1.4          0.2           3.642857
1           4.9          3.0           1.4          0.2           3.500000
2           4.7          3.2           1.3          0.2           3.615385
3           4.6          3.1           1.5          0.2           3.066667
4           5.0          3.6           1.4          0.2           3.571429

   target
0       1
1       1
2       1
3       1
4       1

## Ejercicio 3

In [4]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [10]:
# Instalación (Descomentar si usas Colab)
# !pip install yfinance

import yfinance as yf

# --- Técnica: Importación y variables ---
activo = 'AAPL'
precio = 150.25
precios_lista = [140, 145, 150]
info_dict = {'ticker': activo, 'precios': precios_lista}

print(f"Diccionario financiero: {info_dict}")

Diccionario financiero: {'ticker': 'AAPL', 'precios': [140, 145, 150]}

In [11]:
# --- Laboratorio: Descargar datos de Apple ---
datos = yf.download('AAPL', start='2020-01-01', end='2023-01-01')

print("\nDatos descargados de AAPL (primeras filas):")
print(datos.head())

/tmp/ipykernel_203/2209073645.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  datos = yf.download('AAPL', start='2020-01-01', end='2023-01-01')
[*********************100%***********************]  1 of 1 completed

Datos descargados de AAPL (primeras filas):
Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.400543  72.460807  71.156704  71.409808  135480400
2020-01-03  71.696632  72.455950  71.472454  71.629138  146322800
2020-01-06  72.267937  72.306506  70.568510  70.819208  118387200
2020-01-07  71.928055  72.533095  71.708695  72.277578  108872000
2020-01-08  73.085106  73.386423  71.631552  71.631552  132079200

In [7]:
datos

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2020-01-02   72.400543   72.460807   71.156704   71.409808  135480400
2020-01-03   71.696632   72.455950   71.472454   71.629138  146322800
2020-01-06   72.267937   72.306506   70.568510   70.819208  118387200
2020-01-07   71.928055   72.533095   71.708695   72.277578  108872000
2020-01-08   73.085106   73.386423   71.631552   71.631552  132079200
...                ...         ...         ...         ...        ...
2022-12-23  129.778870  130.330029  127.593906  128.853703   63814900
2022-12-27  127.977760  129.335985  126.688438  129.306460   69007800
2022-12-28  124.050713  128.961953  123.883397  127.623418   85438400
2022-12-29  127.564384  128.420649  125.714059  125.969950   75703700
2022-12-30  127.879318  127.899007  125.418783  126.383319   77034200

[756 rows x 5 columns]

## Ejercicio 4

In [17]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# --- 1. Descargar datos ---
# Descargamos los datos de Apple
datos = yf.download('AAPL', start='2020-01-01', end='2023-01-01')

# CORRECCIÓN: Si el DataFrame tiene MultiIndex (común en nuevas versiones),
# lo aplanamos para que las columnas sean simples: 'Open', 'High', 'Adj Close', etc.
if isinstance(datos.columns, pd.MultiIndex):
    datos.columns = datos.columns.get_level_values(0)

datos.head()

/tmp/ipykernel_203/2061578654.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  datos = yf.download('AAPL', start='2020-01-01', end='2023-01-01')
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Date
2020-01-02  72.400543  72.460807  71.156704  71.409808  135480400
2020-01-03  71.696632  72.455950  71.472454  71.629138  146322800
2020-01-06  72.267937  72.306506  70.568510  70.819208  118387200
2020-01-07  71.928055  72.533095  71.708695  72.277578  108872000
2020-01-08  73.085106  73.386423  71.631552  71.631552  132079200

In [18]:
# --- 2. Cálculos de Retorno ---
# Usamos 'Adj Close' (Cierre ajustado) para el cálculo de retornos
# Si no existiera 'Adj Close', usamos 'Close'
col_precio = 'Adj Close' if 'Adj Close' in datos.columns else 'Close'

# Calcular retornos diarios simples
datos['Retorno_Diario'] = datos[col_precio].pct_change()

# Calcular retorno acumulado
# Fórmula: (1 + r1)*(1 + r2)... - 1
datos['Retorno_Acumulado'] = (1 + datos['Retorno_Diario']).cumprod() - 1

# Mostrar el resultado final
print(f"Retorno acumulado total: {datos['Retorno_Acumulado'].iloc[-1]:.2%}")

Retorno acumulado total: 76.63%

In [19]:
datos.head()

Price,Close,High,Low,Open,Volume,Retorno_Diario,Retorno_Acumulado
Date,,,,,,,
2020-01-02,72.400543,72.460807,71.156704,71.409808,135480400,NaN,NaN
2020-01-03,71.696632,72.455950,71.472454,71.629138,146322800,-0.009722,-0.009722
2020-01-06,72.267937,72.306506,70.568510,70.819208,118387200,0.007968,-0.001832
2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.004703,-0.006526
2020-01-08,73.085106,73.386423,71.631552,71.631552,132079200,0.016086,0.009455